name: Java CI with Maven

on: 
 workflow_dispatch:
  inputs:
   TARGET_ENVIRONMENT:
    type: environment
    default: Dev
   

jobs:
 build:
  runs-on: ubuntu-latest
  environment: ${inputs.TARGET_ENVIRONMENT}
  steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Setup Java JDK
       uses: actions/setup-java@v4
       with:
        java-version: 17
        distribution: microsoft
     - name: Build Using Maven
       run:  mvn clean install
       working-directory: gap_springboot_app
     - name: Upload a Build Artifactory
       uses: actions/upload-artifact@v4
       with:
        name: package
        path: staging
     - run: echo 'vars is ${{vars.VARIABLE}}'
     - run: echo 'secret is ${{vars.SECRET}}'
       
 test:
  runs-on: windows-latest
  needs: build
  steps:
   - name: run test
     run: echo "test"
   
 deploy:
  runs-on: ubuntu-latest
  needs: test
  steps:
   - name: deploy to server
     run: echo 'Deployning an application...!'
       
      

