name: Reusable workflow

on: 
 workflow_call

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: checkout 
     uses: actions/checkout@4.2.0
   - name: Run ReusableBuils Step
     run: echo 'This is a reusable workflow'

  
